backend:
  name: github
  repo: danthelion-git/DanTheLion-Resume
  branch: main

media_folder: "public/uploads"
public_folder: "/DanTheLion-Resume/uploads"

site_url: "https://danthelion-git.github.io/DanTheLion-Resume"

collections:
  - name: "blog"
    label: "Blog posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "description", label: "Description", widget: "text", required: false }
      - { name: "heroImage", label: "Hero Image", widget: "image", required: false }
      - label: "Sections"
        name: "sections"
        widget: "list"
        required: false
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "image", label: "Image", widget: "image" }
          - { name: "caption", label: "Caption", widget: "string", required: false }
          - { name: "body", label: "Body", widget: "markdown", required: false }
      - { name: "body", label: "Main body", widget: "markdown" }
